### PR TITLE
fix for progress bar of xfce4-volumed

### PR DESCRIPTION
**Pull request by ahmubashshir**

### CODE REVIEW

**Comment by MyriaCore** [comment]
Looks good, could you add this usage to the readme? Just in the section demoing "notification with a progress bar", so users know they can use this as well.

**Comment by MyriaCore** [comment]
(not a real reviewer btw, just a tip)

cc @phuhl

**Comment by ahmubashshir** [comment]
ok :3

**Comment by ahmubashshir** [comment]
Done.

**Comment by MyriaCore** [comment]
Awesome, looks good! Hope this gets merged soon.

**Review by phuhl — APPROVED** [review]
Looking good, thanks 👍

**Pull request merged**
