### PR TITLE
Added a *-git-style PKGBUILD

### LINKED ISSUE #84: Create an AUR git package
Name it something like `deadd-notification-center-git` and have it track the head of master. This way, users who want recent updates don't have to build this software outside their package manager. 

It would also mean less people complaining about bumping the version in the AUR.

### PR DESCRIPTION
**Pull request by MyriaCore**
Closes  #84

### CODE REVIEW

**Comment by MyriaCore** [comment]
@phuhl bump?

**Comment by phuhl** [comment]
next week or so, I should be able to do the merges, etc.

**Comment by MyriaCore** [comment]
Alright cool! I won't be able to guarantee fast edits then tho.

Take your time! :heart:

**Review by phuhl — APPROVED** [review]

**Comment by MyriaCore** [comment]
thanks for the merge! :rocket:

**Pull request merged**
