### PR TITLE
Fix ellipsization

### LINKED ISSUE #98: Ellipsization is only enforced over line-wrapped lines
I've been noticing that the ellipsization code has a bug in it.

When working with multi-line bodies that are *also* line wrapped, I tend to get this weird behavior where the notification still stretches wayy lower than my chosen line limit. 

For example, the following notify-send command produces a gigantic notification:

```
notify-send 'Lorem Ipsum' "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent blandit molestie elit, et viverra sem commodo sed. Donec sed iaculis dolor. Proin vitae ex eu odio euismod lobortis. Etiam pretium consequat ligula vel commodo. In tempor magna ut metus posuere, nec elementum sapien suscipit. Fusce scelerisque condimentum metus, in scelerisque justo commodo sed. Fusce ac lorem euismod, porta magna ac, vehicula nulla.

Nullam posuere auctor varius. Curabitur in dui sit amet diam tempor porta ac eget libero. Sed quis felis sit amet ligula accumsan porttitor ut in enim. Quisque quam neque, vestibulum in volutpat varius, faucibus non tortor. Donec vitae neque sollicitudin, elementum ligula egestas, ultrices turpis. Donec porta vel sapien ac vestibulum. Donec rhoncus, tortor at volutpat consequat, orci enim interdum augue, et egestas leo lacus vel purus. Aliquam tempor vestibulum porta. Aliquam sed massa nec purus sollicitudin commodo. Donec vulputate massa quis eros pretium ullamcorper. Maecenas efficitur tortor at nisi lacinia, ac consequat ligula consequat. Aliquam consectetur metus ut tellus viverra, condimentum consequat mauris ornare. Nullam cursus orci id sodales efficitur. Pellentesque ultrices arcu congue sapien blandit, at sagittis risus dignissim.

Sed a dui vel ipsum pharetra aliquam. Phasellus sit amet fermentum urna. Sed porttitor mauris ante, eget tempus lacus viverra et. Sed et condimentum massa. Cras arcu lacus, venenatis ac nulla sed, mattis porta nisl. Aenean id massa sit amet augue elementum aliquam et vel enim. Donec mattis diam eu ipsum interdum, vitae mollis odio fringilla.

Ut non eros vitae sem accumsan tempus eu id dolor. Donec viverra pellentesque dui, at sagittis ligula condimentum vel. Donec eleifend dapibus nunc vel auctor. In ut quam eu massa commodo vestibulum. Morbi sit amet leo erat. Sed dignissim, mi eget consectetur pharetra, mi massa accumsan purus, sed commodo orci nisl vitae neque. Aliquam quis feugiat urna. Suspendisse neque enim, dapibus nec ullamcorper eget, consequat ornare sem.

Aliquam sit amet lorem mattis, fringilla mauris sit amet, aliquet ex. Mauris sit amet rutrum lectus. Nulla turpis neque, dictum sit amet sollicitudin vitae, mollis eget lacus. Donec at orci congue nibh dignissim molestie sit amet nec arcu. Maecenas elementum ex sed leo ornare pharetra. Integer laoreet finibus neque commodo efficitur. Nulla mollis at eros sit amet facilisis. Etiam id tempor orci, et hendrerit tellus. Quisque fringilla, risus sed commodo fermentum, dolor arcu lacinia turpis, eget aliquet mauris risus nec eros. Fusce at lacus sed odio convallis egestas ut a sem."
```

image

As you can see, each *paragraph* is allowed to render, but is cut off at 5 lines. So, it appears that the 5 line ellipsization rule is only being enforced on a per-paragraph basis, rather than across the entire notification. 

It's important to note here that each **real line** in the text appears as a paragraph to us because of GTK's line wrapping, which breaks the text up. We need to make a distinction between real lines, which are the paragraph breaks, and line-wrapped lines, which are the lines that *we see* which make up the paragraph.

So, what's happening here, ultimately, is that ellipsization only appears to operate over *line-wrapped* lines, and not over the entire message. In this case, intended behavior would be for ellipsization operate once over the entire body, and to count both line-wrapped lines *and* real lines. This way, once 5 lines appear on the notification body, the ellipsization comes in to save your screen real-estate.

### PR DESCRIPTION
**Pull request by MyriaCore**
Closes #98. Implements the algorithm described below:

<blockquote>

- [labelGetLayout](https://www.stackage.org/haddock/lts-16.7/gi-gtk-3.0.33/GI-Gtk-Objects-Label.html#v:labelGetLayout) will return the [Layout](https://www.stackage.org/haddock/lts-16.7/gi-pango-1.0.22/GI-Pango-Objects-Layout.html) of a given label for us, which can help us see how many rendered lines there would be
- [layoutGetLineCount](https://www.stackage.org/haddock/lts-16.7/gi-pango-1.0.22/GI-Pango-Objects-Layout.html#v:layoutGetLineCount) returns the number of lines after line wrapping which we can use to check against our max line count (as configured by the user)
- If there are too many lines, [layoutGetLines](https://www.stackage.org/haddock/lts-16.7/gi-pango-1.0.22/GI-Pango-Objects-Layout.html#v:layoutGetLines) will return a list of [LayoutLines](https://www.stackage.org/haddock/lts-16.7/gi-pango-1.0.22/GI-Pango-Structs-LayoutLine.html), which won't be *directly* useful, but will allow us to get the LayoutLine of the last line we'll allow. 
- Now that we have the LayoutLine of the last line we want to allow, we need to figure out where the third-to-last character on that line is *in the text* so we can truncate there and add a `...`. We can do this with the following (I think):
  * <code><a href='https://www.stackage.org/haddock/lts-16.7/gi-pango-1.0.22/GI-Pango-Structs-LayoutLine.html#g:14'>the length</a> - 4</code> will get us the index of the third-to-last byte in the line
  * Add that to [the start index of the line](https://www.stackage.org/haddock/lts-16.7/gi-pango-1.0.22/GI-Pango-Structs-LayoutLine.html#g:17) to get the actual text index of this byte
  * Pray that 1 byte = 1 character because that's the only way this algorithm will work
- Finally, we change the character at the resulting index to a `.`, and then change the next 2 characters to a `.` as well, and truncate the text there. We'll call `labelSetText` or something to make the change. 
</blockquote>

### Caveats

To rush this out so users could have a good experience, this only works for popup notifications - *not* in-center notifications. See [discussion](https://github.com/phuhl/linux_notification_center/pull/110#issuecomment-758869045) for more information.

### CODE REVIEW

**Comment by MyriaCore** [comment]
Running `notify-send '40 numbers' "$(seq 40)"` gives me the following popup:

image

Things appear to be fixed. As a stress test, I also ran on the following output: 

<details>

```
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Proin eget ex nec metus commodo pulvinar.
    Curabitur sed mi sit amet neque volutpat pharetra ac eget enim.

    In aliquam turpis et turpis gravida consectetur.
    Morbi commodo augue porta mauris sodales, ac posuere elit ornare.
    Phasellus in lectus ac enim bibendum consequat.
    Nam luctus felis vel justo mattis, sed sagittis nunc accumsan.

    Duis non est iaculis, ullamcorper lacus ac, rhoncus ligula.
    Vivamus hendrerit ipsum tempus, ultrices lorem ut, elementum orci.

    Etiam sodales dolor sollicitudin sem interdum, ac imperdiet tellus tempor.

    Aliquam eget libero et magna lobortis ornare.

    Donec et mauris consectetur, facilisis odio vel, interdum elit.

    Integer non neque dapibus, pretium enim id, sagittis nulla.
    Donec a sem porttitor, rutrum nisl eget, laoreet nibh.
    Fusce ut eros auctor, condimentum ante et, suscipit erat.
    Morbi at dui tristique lectus finibus efficitur sit amet sed justo.

    Donec ac nunc pretium sem efficitur vestibulum.
    Praesent a quam nec ipsum fermentum iaculis.
    Nullam at justo sed nunc ornare dignissim.
    Sed luctus metus at scelerisque lobortis.

    Quisque sed magna tempor, vehicula tortor ac, euismod ex.

    Vivamus hendrerit nisl at sapien lobortis auctor.
    Donec quis nisl efficitur, pharetra mauris sed, congue lacus.
    Sed aliquam libero ac dolor feugiat, eget maximus lectus posuere.
    Praesent nec diam viverra, semper est et, semper erat.
    Suspendisse nec turpis eu erat vulputate consequat.

    Curabitur at quam vitae quam tincidunt eleifend vel id ipsum.
    Sed mollis lacus quis neque scelerisque, quis vehicula sapien auctor.
    Nulla convallis sem vel elit tincidunt, ut tempus tellus placerat.
    Cras consectetur ligula et orci placerat, eu ultricies justo lobortis.
    Cras porttitor nibh ac cursus fringilla.
    Proin sed dolor eget mauris sodales malesuada.

    Phasellus sit amet ex in nulla luctus rhoncus eget sit amet erat.
    Vestibulum consectetur nisl ultrices, congue dui nec, congue tortor.
    Donec cursus turpis vel dolor ultrices, quis aliquam neque condimentum.

    Donec vitae nibh eu metus faucibus volutpat.
    Maecenas ac sem gravida leo hendrerit consequat.
    Mauris quis tellus eu tortor auctor laoreet.
    Morbi vulputate neque consectetur, iaculis felis a, tempus libero.

    Integer at eros luctus, aliquet libero in, efficitur libero.
    Sed nec tortor eleifend dui egestas efficitur.
    Integer eget tellus gravida dui tincidunt bibendum.
    Nullam ullamcorper risus vulputate rhoncus viverra.

    Nulla eu justo non felis ullamcorper aliquam ac sed justo.
    Nulla vehicula elit a massa malesuada, ac dictum sapien posuere.

    Donec sit amet urna mollis, rutrum purus eu, mattis metus.
    Sed sed sapien sed quam pharetra laoreet in sit amet sem.
    Phasellus vel nulla consequat, condimentum risus eu, pretium dolor.
    Duis fringilla nibh eu enim auctor suscipit.
    Ut nec quam ut dolor suscipit pulvinar eget sit amet massa.
    Praesent condimentum eros sit amet nunc suscipit facilisis.

    Pellentesque iaculis tellus sed dolor venenatis porttitor.
    Vestibulum a nunc quis justo elementum laoreet non non mi.
    Pellentesque finibus nisi nec nisi porttitor, at luctus mi rutrum.
    Donec ullamcorper risus sed ligula scelerisque blandit.
    Vestibulum in sapien eu dolor euismod consequat at quis neque.
    Donec commodo lectus eu elit aliquam ultrices.

    Sed fringilla odio ac velit tincidunt, id porttitor ipsum scelerisque.
    Curabitur in massa imperdiet, vestibulum urna finibus, fermentum tortor.
    Fusce ac enim vel eros aliquet iaculis eget sit amet dolor.
    Maecenas non nibh dictum, dapibus arcu nec, malesuada metus.
    Nulla vitae lectus vitae ipsum volutpat vestibulum at ultricies magna.

    Fusce ac risus quis libero feugiat eleifend ut eu mi.
    Morbi pulvinar diam ut diam convallis fringilla.
    Aenean vitae enim at nibh semper bibendum.
    Sed et risus ac nulla dignissim elementum.
    Vivamus vestibulum augue consectetur, bibendum nibh et, ornare metus.

    Proin non nisi elementum, venenatis enim non, ullamcorper magna.
    Cras et eros at sem blandit efficitur.
```
</details>

Running on this gives me the following popup:

image

Hopefully things stay stable with this implementation.

**Comment by MyriaCore** [comment]
I've been trying to implement this for [Notifications in the notification center](https://github.com/phuhl/linux_notification_center/blob/792fe95d71f6974bae27e5501675ec43eb95241d/src/NotificationCenter/NotificationInCenter.hs), but I'm **really** struggling. I'm running into this weird behavior where `layoutGetLines` always returns the entire text block as 1 line, even though it's *obvious* that there are multiple lines being wrapped. 

I did run into this bug when implementing this for popups, but I think I solved it by having the ellipsization happen *after* we set the height. The docs seem to suggest that these functions are kinda height-sensitive. However, we don't really *explicitly* set the height in the code for in-notification stuff, so I'm kinda screwed. I'm gonna ask around in some GTK forums to see if people know why things are behaving like this.

**Comment by phuhl** [comment]
> I've been trying to implement this for Notifications in the notification center, but I'm really struggling. I'm running into this weird behavior where layoutGetLines always returns the entire text block as 1 line, even though it's obvious that there are multiple lines being wrapped.

Maybe it's due to https://github.com/phuhl/linux_notification_center/issues/103 and the notifications are just extremely wide?

**Comment by MyriaCore** [comment]
Wow, I didn't even know about that. Not sure if this is why, though. Ultimately, my guess is as good as yours.

**Comment by MyriaCore** [comment]
It totally could be a width thing too. I'm just not super sure.

**Comment by phuhl** [comment]
> This kinda creates a problem though, since I don't think it's really possible to set the height of an in-center notification as though it were a window, right? The only reason we could do that for popups is because they made a window for themselves, correct?

I think, that works. My main issue always was, that you can *only* specify the height and not the width, that's why I used that hackish workaround to calulate the height for a desired width and then set the resulting height. Thats how we achieve the width of the pop-ups currently (iirc) and that's also why this stuff brakes, I think.

**Comment by MyriaCore** [comment]
Alright so I just did a really quick test to see if things worked in light of the fix for #103. I used `notify-send '40 numbers' "$(seq 40)"` to test 450a593, which is a super hasty port of the algorithm I described earlier, and it doesn't even trip. Once again, for whatever reason, the pango line layout stuff isn't recognizing the `\n`'s as line breaks in the notification center.

**Comment by MyriaCore** [comment]
Honestly, I think this issue is important enough that we should split this PR. I think we should remove the notification center's `shortenBody` option, and ship this for popups. Then we'll bring it back in another PR once we figure out how to make it work.

**Comment by MyriaCore** [comment]
Alright, I removed the WIP in-center stuff and just have the popup code. [In my testing](https://github.com/phuhl/linux_notification_center/pull/110#issuecomment-734990014) it works pretty well.

**Comment by phuhl** [comment]
Wtf GTK that one has to implement stuff like that manually... 

Anyways, looking good.

> Pray that 1 byte = 1 character because that's the only way this algorithm will work

If I understand the documentation of [Data.Text](https://hackage.haskell.org/package/text-1.2.4.0/docs/Data-Text.html) correctly, then Data.Text handles this problem for us already and we can only operate on complete characters.

**Review by phuhl — APPROVED** [review]

**Comment by MyriaCore** [comment]
> Wtf GTK that one has to implement stuff like that manually...

Yeah, definitely strange. Might be worth writing a proposal for, since it's technically all open source over [on gitlab](https://gitlab.gnome.org/GNOME/gtk).

**Pull request merged**
