### PR TITLE
Bump version

### LINKED ISSUE #90: Bump version (for AUR and for published releases)
After #89, #86, and possibly #78 are merged, I think it's around time we should bump the version, including the binary version.

AFAIK, to update the binary version, someone just has to try to build this package and commit the `.out/deadd-notification-center`. I can totally do that no sweat, I just don't want to do it without having merged the other features.

This will alleviate some badness from #85/#45, since users could just grab this instead of having to deal with the weird build errors.

### PR DESCRIPTION
**Pull request by MyriaCore**
Closes #90. 

**Note:** I've included binaries in the `.out` folder of this PR, so anyone who is being affected by #85/#45 can work around it with the following steps:

1. Clone my fork, checkout the `bump-vers` branch and pull
2. remove the existing installation of deadd (either through your package manager, or by running `sudo make uninstall`)
3. Run `sudo make install` to install the pre-built binaries, no stack necessary!

# IMPORTANT!

When merging:
1. tag this as release version `1.7.3`. The PKGBUILDs have all been updated for that version. 
2. Upload the updated PKGBUILDS to the AUR: [deadd-notification-center](https://aur.archlinux.org/packages/deadd-notification-center/) and [deadd-notification-center-bin](https://aur.archlinux.org/packages/deadd-notification-center-bin/)
3. Create a new package in the AUR called [deadd-notification-center-git](https://aur.archlinux.org/packages/deadd-notification-center-git/) with the PKGBUILD located at `pkg-git/PKGBUILD`.

### CODE REVIEW

**Comment by phuhl** [comment]
Thanks for helping out and I'd love your dev power on the project anytime again in the future 💪

**Comment by tpurde** [comment]
Is this close to merging?

**Comment by MyriaCore** [comment]
apparently not lmao

**Comment by phuhl** [comment]
I might be slow, but... yeah, I am slow!

**Comment by MyriaCore** [comment]
Nice! One last note, we should probably add git to makedepends as per this [AUR user's suggestion](https://aur.archlinux.org/packages/deadd-notification-center-git/#comment-771110).

**Comment by phuhl** [comment]
Yeah, I saw that, gonna do it later today

**Pull request merged**
