### PR TITLE
Better default text formatting

### LINKED ISSUE #75: Better Default Text Formatting in Popups
The default formatting for text in popups is honestly kinda not great:

<table>
<tr>
<th>Linux Notif Center</th>
<th>Dunst</th>
</tr>

<tr>
<td>

image
</td>
<td>

image
</td>
</tr>
</table>

* Screenshots courtesy of @tpurde

A few notes:
- Body text shouldn't grow the size of the notification. Instead, it should be cutoff with `(...)`. 
- The image should be centered vertically by default. The vertical alignment should also be configurable. 
- There should be configurable margins around the image.

### PR DESCRIPTION
**Pull request by MyriaCore**
Closes #75.

- [x] Body text shouldn't grow the size of the notification. Instead, it should be cutoff with `(...)` at about 2-5 lines
  - We should probably expose a setting for this too, so the user can choose how many lines they want. 
- [x] ~~The image should be centered vertically by default~~
   - ~~There should *definitely* be a setting for vertically centering the image, or having it in the corner, etc.~~ 
   
   Deemed out of scope / not enough time to implement. See discussion: https://github.com/phuhl/linux_notification_center/pull/78#issuecomment-687177834
- [x] There should be configurable margins around the image.

#### New Config vars

```ini
[notification-center]

# Truncates notification bodies with '...' at the specified number of 
# lines. If -1 is specified, the body text will not be truncated.
# Applies only to notifications within the notification center. 
shortenBody = -1

[notification-center-notification-popup]

# The margin around the top, bottom, left, and right of notification
# images. Applies to popup notifications and in-center notifications.
imageMarginTop = 15
imageMarginBottom = 15
imageMarginLeft = 15
imageMarginRight = 0


# Truncates notification bodies with '...' at the specified number of 
# lines. If -1 is specified, the body text will not be truncated.
# Applies only to popup notifications
shortenBody = 5
```
(Also, I turned the `BEGIN_EXAMPLE` block into a `BEGIN_SRC ini` in the readme, so we can have some nice syntax highlighting for the example config :D)

### CODE REVIEW

**Comment by MyriaCore** [comment]
I'm kinda struggling to deal w/ the semi-diverging histories here. 4da6094f6c1f0e9561e0eb4ce7ef26b00acdbd97 shouldn't do anything when applied to here, it's basically just to re-sync my fork. Not sure how to get rid of it lol

**Comment by MyriaCore** [comment]
I thought the elipsization edit would be quick and easy, but I'm getting a weird bug in the notification center with the fonts:

<table>
<tr>
  <th>With edit</th>
  <th>Without edit</th>
</tr>

<tr>
<td>

image
</td>
<td>

image
</td>
</tr>
</table>

The glade files don't say anything about font sizing, so I assume that this happens somewhere. I *don't* think it's a config issue. Not sure where it's coming from, though.

**Comment by MyriaCore** [comment]
Might be cleaner going through code. There's a [`labelSetEllipsize`](https://www.stackage.org/haddock/lts-16.7/gi-gtk-3.0.33/GI-Gtk-Objects-Label.html#v:labelSetEllipsize) function that we could use on the body [here](https://github.com/phuhl/linux_notification_center/blob/e67ef7214d7948e90b4ae4e7f1f6d80536034aa2/src/NotificationCenter/Notifications/AbstractNotification.hs#L55-L89). This would also be a perfect place to get the config variable from too.

**Comment by MyriaCore** [comment]
No, the font swaping is *still* happening in-center:
image

This is honestly super strange.

**Comment by MyriaCore** [comment]
Alright, I'm starting to think that this might be some weird bug on my machine, or just some weird bug in general, because I tried testing this with the following edit, and it *should* literally just be the same code that's currently on `master`, but it's still giving me this weird new bug. 

```diff
diff --git a/src/NotificationCenter/Notifications/NotificationPopup.hs b/src/NotificationCenter/Notifications/NotificationPopup.hs
index d4ac9c1..4334372 100644
--- a/src/NotificationCenter/Notifications/NotificationPopup.hs
+++ b/src/NotificationCenter/Notifications/NotificationPopup.hs
@@ -85,13 +85,13 @@ showNotificationWindow config noti dispNotis onClose = do
         dispNotiWithoutHeight
       lblBody = (flip view) dispNoti $ dLabelBody
 
-  labelSetEllipsize lblBody EllipsizeModeEnd 
+  -- labelSetEllipsize lblBody EllipsizeModeEnd 
     -- if configPopupEllipsizeBody config
     -- then EllipsizeModeEnd
     -- else EllipsizeModeNone
 
   -- TODO: Integrate w/ config
-  labelSetLines lblBody 5
+  -- labelSetLines lblBody 5
 
   setWidgetWidthRequest mainWindow $ fromIntegral $ configWidthNoti config
```

@phuhl I don't wanna bother you, but could you do me a huge favor and try running this on your machine to see if it gives u this bug? I really just wanna move past this rn, and I have no clue where it could be coming from.

**Comment by phuhl** [comment]
Compiles and runs without that wierd bug, but also it does not ellipzise on my machine... Don't know if i am doing smth wrong?

**Comment by phuhl** [comment]
org_20200826_112612_GXwiRN

org_20200826_112731_O9Zv6k

So, does not work. Same bug as yours. And, coincidentially, shows another bug that I did'nt manage to track down yet, where the content area of the notification center sometimes is too short.

**Comment by phuhl** [comment]
That error exists on the base branch already

**Comment by phuhl** [comment]
Yeah, quite sure, the bug was introduced in d5fd02fd8325a692340c632bd1aab4895608c948 which I carelessly merged because I though reading the changes is sufficient. Sorry bout that.

**Comment by phuhl** [comment]
Patch style.css and it works:

```css
 .time {
-    font-size: replaceme0027;
+    font-size: replaceme0028;
 }
 
 .noti-center.time {
-    font-size: replaceme0028;
+    font-size: replaceme0027;
 }
```

Would you mind, introducing the css patch in this PR? Then we could be done with it! @MyriaCore

**Comment by MyriaCore** [comment]
Prob shouldn't have fixed in master, u *should* have write perms for this PR. Lemme try to merge the master in.

**Comment by MyriaCore** [comment]
Nice, this patch is working for me too! Still getting that notification area bug though. That'll probably be for another PR.

**Comment by MyriaCore** [comment]
Alright, I think this PR is pretty much finished, other than the proposal over in https://github.com/phuhl/linux_notification_center/issues/75#issuecomment-681123153. At the moment, here's what images look like w/ default settings: 

image

**Comment by MyriaCore** [comment]
Alright, I'm trying to figure out how to implement the suggestion I made in https://github.com/phuhl/linux_notification_center/issues/75#issuecomment-681123153. I made the following changes to `notification.glade`:

<details>
<summary>View Diff</summary>

```diff
diff --git a/notification.glade b/notification.glade
index 8179557..6eb7493 100644
--- a/notification.glade
+++ b/notification.glade
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<!-- Generated with glade 3.22.2 -->
+<!-- Generated with glade 3.36.0 -->
 <interface>
   <requires lib="gtk+" version="3.20"/>
   <!-- interface-css-provider-path style.css -->
@@ -10,9 +10,6 @@
     <property name="vexpand">True</property>
     <property name="type">popup</property>
     <property name="resizable">False</property>
-    <child type="titlebar">
-      <placeholder/>
-    </child>
     <child>
       <object class="GtkOverlay">
         <property name="visible">True</property>
@@ -29,120 +26,57 @@
           </packing>
         </child>
         <child type="overlay">
-          <object class="GtkBox" id="box_container">
+          <object class="GtkBox">
             <property name="visible">True</property>
             <property name="can_focus">False</property>
+            <property name="orientation">vertical</property>
             <child>
-              <object class="GtkImage" id="img_img">
-                <property name="visible">True</property>
-                <property name="can_focus">False</property>
-                <property name="valign">start</property>
-                <property name="vexpand">True</property>
-                <property name="pixel_size">185</property>
-                <property name="icon_size">0</property>
-                <style>
-                  <class name="deadd-noti-center"/>
-                  <class name="notification"/>
-                  <class name="image"/>
-                </style>
-              </object>
-              <packing>
-                <property name="expand">False</property>
-                <property name="fill">True</property>
-                <property name="position">0</property>
-              </packing>
-            </child>
-            <child>
-              <object class="GtkBox">
+              <object class="GtkBox" id="box_container">
                 <property name="visible">True</property>
                 <property name="can_focus">False</property>
-                <property name="margin_left">15</property>
-                <property name="margin_right">10</property>
-                <property name="vexpand">True</property>
-                <property name="orientation">vertical</property>
-                <property name="baseline_position">bottom</property>
                 <child>
-                  <object class="GtkLabel" id="label_titel">
+                  <object class="GtkImage" id="img_img">
                     <property name="visible">True</property>
                     <property name="can_focus">False</property>
-                    <property name="halign">start</property>
                     <property name="valign">start</property>
-                    <property name="margin_top">10</property>
-                    <property name="label" translatable="yes">Titel</property>
-                    <property name="wrap">True</property>
-                    <property name="wrap_mode">word-char</property>
+                    <property name="vexpand">True</property>
+                    <property name="pixel_size">185</property>
+                    <property name="icon_size">0</property>
                     <style>
-                      <class name="notification"/>
-                      <class name="title"/>
                       <class name="deadd-noti-center"/>
-                    </style>
-                  </object>
-                  <packing>
-                    <property name="expand">False</property>
-                    <property name="fill">False</property>
-                    <property name="position">0</property>
-                  </packing>
-                </child>
-                <child>
-                  <object class="GtkLabel" id="label_body">
-                    <property name="visible">True</property>
-                    <property name="can_focus">False</property>
-                    <property name="halign">start</property>
-                    <property name="valign">start</property>
-                    <property name="use_markup">True</property>
-                    <property name="wrap">True</property>
-                    <style>
                       <class name="notification"/>
-                      <class name="body"/>
-                      <class name="deadd-noti-center"/>
+                      <class name="image"/>
                     </style>
                   </object>
-                  <packing>
-                    <property name="expand">False</property>
-                    <property name="fill">False</property>
-                    <property name="position">1</property>
-                  </packing>
-                </child>
-                <child>
-                  <object class="GtkBox" id="box_actions">
-                    <property name="visible">True</property>
-                    <property name="can_focus">False</property>
-                    <property name="halign">center</property>
-                    <child>
-                      <placeholder/>
-                    </child>
-                    <child>
-                      <placeholder/>
-                    </child>
-                    <child>
-                      <placeholder/>
-                    </child>
-                  </object>
                   <packing>
                     <property name="expand">False</property>
                     <property name="fill">True</property>
-                    <property name="position">2</property>
+                    <property name="position">0</property>
                   </packing>
                 </child>
                 <child>
-                  <object class="GtkBox">
+                  <object class="GtkBox" id="notif_content">
                     <property name="visible">True</property>
                     <property name="can_focus">False</property>
-                    <property name="halign">end</property>
+                    <property name="margin_left">15</property>
+                    <property name="margin_right">10</property>
+                    <property name="vexpand">True</property>
+                    <property name="orientation">vertical</property>
+                    <property name="baseline_position">bottom</property>
                     <child>
-                      <object class="GtkImage" id="img_icon">
-                        <property name="width_request">10</property>
-                        <property name="height_request">10</property>
+                      <object class="GtkLabel" id="label_titel">
                         <property name="visible">True</property>
                         <property name="can_focus">False</property>
-                        <property name="halign">end</property>
-                        <property name="valign">end</property>
-                        <property name="margin_right">10</property>
-                        <property name="icon_size">0</property>
+                        <property name="halign">start</property>
+                        <property name="valign">start</property>
+                        <property name="margin_top">10</property>
+                        <property name="label" translatable="yes">Titel</property>
+                        <property name="wrap">True</property>
+                        <property name="wrap_mode">word-char</property>
                         <style>
-                          <class name="deadd-noti-center"/>
                           <class name="notification"/>
-                          <class name="icon"/>
+                          <class name="title"/>
+                          <class name="deadd-noti-center"/>
                         </style>
                       </object>
                       <packing>
@@ -152,48 +86,122 @@
                       </packing>
                     </child>
                     <child>
-                      <object class="GtkLabel" id="label_appname">
+                      <object class="GtkLabel" id="label_body">
                         <property name="visible">True</property>
                         <property name="can_focus">False</property>
-                        <property name="halign">end</property>
-                        <property name="label" translatable="yes">Appname</property>
+                        <property name="halign">start</property>
+                        <property name="valign">start</property>
+                        <property name="use_markup">True</property>
+                        <property name="wrap">True</property>
                         <style>
                           <class name="notification"/>
-                          <class name="appname"/>
+                          <class name="body"/>
                           <class name="deadd-noti-center"/>
                         </style>
                       </object>
                       <packing>
                         <property name="expand">False</property>
-                        <property name="fill">True</property>
+                        <property name="fill">False</property>
                         <property name="position">1</property>
                       </packing>
                     </child>
+                    <child>
+                      <object class="GtkBox" id="app_container">
+                        <property name="visible">True</property>
+                        <property name="can_focus">False</property>
+                        <property name="halign">end</property>
+                        <child>
+                          <object class="GtkImage" id="img_icon">
+                            <property name="width_request">10</property>
+                            <property name="height_request">10</property>
+                            <property name="visible">True</property>
+                            <property name="can_focus">False</property>
+                            <property name="halign">end</property>
+                            <property name="valign">end</property>
+                            <property name="icon_size">0</property>
+                            <style>
+                              <class name="deadd-noti-center"/>
+                              <class name="notification"/>
+                              <class name="icon"/>
+                            </style>
+                          </object>
+                          <packing>
+                            <property name="expand">False</property>
+                            <property name="fill">False</property>
+                            <property name="position">0</property>
+                          </packing>
+                        </child>
+                        <child>
+                          <object class="GtkLabel" id="label_appname">
+                            <property name="visible">True</property>
+                            <property name="can_focus">False</property>
+                            <property name="halign">end</property>
+                            <property name="label" translatable="yes">Appname</property>
+                            <style>
+                              <class name="notification"/>
+                              <class name="appname"/>
+                              <class name="deadd-noti-center"/>
+                            </style>
+                          </object>
+                          <packing>
+                            <property name="expand">False</property>
+                            <property name="fill">True</property>
+                            <property name="position">1</property>
+                          </packing>
+                        </child>
+                      </object>
+                      <packing>
+                        <property name="expand">False</property>
+                        <property name="fill">False</property>
+                        <property name="padding">8</property>
+                        <property name="position">2</property>
+                      </packing>
+                    </child>
                   </object>
                   <packing>
-                    <property name="expand">False</property>
-                    <property name="fill">False</property>
-                    <property name="padding">8</property>
-                    <property name="position">3</property>
+                    <property name="expand">True</property>
+                    <property name="fill">True</property>
+                    <property name="pack_type">end</property>
+                    <property name="position">1</property>
                   </packing>
                 </child>
+                <style>
+                  <class name="deadd-noti-center"/>
+                  <class name="notification"/>
+                  <class name="container"/>
+                </style>
               </object>
               <packing>
-                <property name="expand">True</property>
+                <property name="expand">False</property>
+                <property name="fill">True</property>
+                <property name="position">0</property>
+              </packing>
+            </child>
+            <child>
+              <object class="GtkBox" id="box_actions">
+                <property name="visible">True</property>
+                <property name="can_focus">False</property>
+                <property name="halign">center</property>
+                <child>
+                  <placeholder/>
+                </child>
+                <child>
+                  <placeholder/>
+                </child>
+              </object>
+              <packing>
+                <property name="expand">False</property>
                 <property name="fill">True</property>
-                <property name="pack_type">end</property>
                 <property name="position">1</property>
               </packing>
             </child>
-            <style>
-              <class name="deadd-noti-center"/>
-              <class name="notification"/>
-              <class name="container"/>
-            </style>
           </object>
         </child>
       </object>
     </child>
+    <child type="titlebar">
+      <placeholder/>
+    </child>
     <style>
       <class name="blurredBG"/>
       <class name="notification"/>
```
</details>

This appears to compile and work, but action buttons just don't show up at all. I'm super confused, am I missing something? I can't find anywhere in the code where the specific structure of the heirarchy mattered - this `getobj` function seems to always just pick out a specific gtk widget by name.

**Comment by MyriaCore** [comment]
I modified `AbstractNotification.hs` to print out if there were actions, and if actionIcons were enabled.

<details>
<summary>View Diff</summary>

```diff
diff --git a/src/NotificationCenter/Notifications/AbstractNotification.hs b/src/NotificationCenter/Notifications/AbstractNotification.hs
index ee73729..450d061 100644
--- a/src/NotificationCenter/Notifications/AbstractNotification.hs
+++ b/src/NotificationCenter/Notifications/AbstractNotification.hs
@@ -18,6 +18,7 @@ import NotificationCenter.Notifications.Action
   (Action(..), createAction)
 import TransparentWindow (label, image, box, getObjs, addClass)
 
+import qualified Data.Text.IO as TIO
 import Data.Text as Text
 import Data.Int ( Int32 )
 
@@ -30,8 +31,8 @@ import GI.Gtk (widgetShowAll, widgetHide, windowMove, widgetDestroy
               , labelSetMarkup, widgetSetSizeRequest, labelSetXalign 
               , widgetGetPreferredHeightForWidth, onWidgetButtonPressEvent
               , imageSetFromPixbuf, imageSetFromIconName, setWidgetWidthRequest
-              , setImagePixelSize, widgetSetMarginStart, widgetSetMarginEnd
-              , catchGErrorJustDomain, GErrorMessage(..))
+              , setImagePixelSize, catchGErrorJustDomain, GErrorMessage(..)
+              , widgetGetName)
 import GI.GLib (FileError(..))
 import GI.GdkPixbuf (pixbufScaleSimple, pixbufGetHeight, pixbufGetWidth
                     , Pixbuf(..), pixbufNewFromFileAtScale
@@ -99,6 +100,8 @@ createNotification config builder noti dispNoti = do
     notiOnAction noti "default"
     return False
 
+  widgetGetName actions >>= TIO.putStrLn
+  (Gtk.containerGetChildren actions) >>= mapM_ (\c -> widgetGetName c >>= TIO.putStrLn) 
 
   return
     $ set dLabelTitel labelTitel
```
</details>

The name of the action box is correctly printed, but the actions aren't. It's almost like the actions weren't even parsed. 

The command I'm testing with is:

```sh
notify-send.py "Sqortal" "squirtle is VERY confused" \
  -a 'sqortal' -i raindrop \
  --hint 'string:image-path:file://home/myriacore/Pictures/sqortal.gif' \
  --action '1:VERY confused' &
```

My normal notif daemon handles this well. Not sure what the problem is here.

**Comment by MyriaCore** [comment]
Did a few more tests. I put a print statement in [`AbstractNotification.updateNotiContent`](https://github.com/MyriaCore/linux_notification_center/blob/861c37055020185fc111839d9a3c15a9f1b31315/src/NotificationCenter/Notifications/AbstractNotification.hs#L125-L155) to see if the `Notification` itself actually did have the actions, and it did. It even appears that the list of [`actionButtons`](https://github.com/MyriaCore/linux_notification_center/blob/861c37055020185fc111839d9a3c15a9f1b31315/src/NotificationCenter/Notifications/AbstractNotification.hs#L145-L148) has the correct amount of buttons, so I do get the sense that the right thing is happening here. I even threw the following line just before the return to verify that the length of the updated `actionButtons` was the same as the number of new children, and that was also the case as well:

```haskell
  Gtk.containerGetChildren (view dActions dNoti) >>= putStrLn . show . Prelude.length
```

This kinda implies that if stuff is going wrong in this function, the only place it could be happening is [here](https://github.com/MyriaCore/linux_notification_center/blob/861c37055020185fc111839d9a3c15a9f1b31315/src/NotificationCenter/Notifications/AbstractNotification.hs#L153). I tested a bit more by putting the following lines *after* the`widgetShowAll` thing:

```haskell
  Gtk.containerGetChildren (view dActions dNoti) >>= putStrLn . show . Prelude.length

  liftIO $ do 
    children <- Gtk.containerGetChildren (view dActions dNoti)
    children' <- filterM widgetIsVisible children
    putStrLn $ show $ Prelude.length children'
```

This definitively proves it. There *are* children in `(view dActions dNoti)` after the call to `widgetShowAll (view dActions dNoti)`, they're just not visible for whatever reason. Maybe `(view dActions dNoti)` is a good reference for getting data back, but a bad reference for setting data?

**Comment by MyriaCore** [comment]
At first I thought this was happening b/c maybe the parent of `box_actions` is hidden, so it's forcing `box_actions` to hide as well, even though we're trying to show it. But, `box_actions` and `box_container` share the same parent, so the same thing would have to be happening to the other notif content. Not sure why things are all upset.

**Comment by MyriaCore** [comment]
I am *beyond* confused rn. I added this snippet below to test the whole 'is the parent hidden too' theory, just to be safe:

```haskell
  let getParent w  = liftIO $ do
        mp <- widgetGetParent w
        return $ fromJust mp
        
  let parentVisible w = liftIO $ do
        p <- getParent w
        widgetIsVisible p

  parentVisible (view dActions dNoti) >>= parentVisible >>= putStrLn . show
  -- ^ Prints "False"
  getParent (view dActions dNoti) >>= parentVisible >>= putStrLn . show
  -- ^ Also prints "False"
```
This stuff went after the `widgetShowAll` thing. Apparently, not only is the *parent* hidden, but the *parent's parent* is supposedly hidden. So, not only is `box_container` supposedly hidden, but the `GtkOverlay` that's holding everything is also hidden. By this logic, the notification shouldn't ever even show up. Maybe, what's happening is that the *original notification* is allowed to display, but the 'updated notification' never can, for whatever reason. I don't think gtk has a transaction system, but maybe there's something happening such that the original notification is allowed to display, but maybe when updating we made a 'bad edit', so gtk is refusing to display the updated notification.

**Comment by MyriaCore** [comment]
Alright, I just pushed the changes I made to the glade, and to the code in [`AbstractNotification.updateNotiContent`](https://github.com/MyriaCore/linux_notification_center/blob/861c37055020185fc111839d9a3c15a9f1b31315/src/NotificationCenter/Notifications/AbstractNotification.hs#L125-L155). This code adds a **known bug** where notification action buttons never appear, even when specified. 

To reproduce this bug:

1. Send a notification with actions in it. For example:
```sh
   notify-send.py "Lorem" "Lorem Ipsum"  \
     -a 'lorem' -i 'text-plain' \
     --action '1:Action One' '2:Action Two' &
   ```
2. Look at output of notification daemon
3. Bugged output looks something like this:
   ```
   Number of action buttons after `widgetShowAll`: 2
   Number of *visible* action buttons after `widgetShowAll`: 0
   Parent of `box_actions` is NOT visible!
   Grandparent of `box_actions` is NOT visible!
   --------------------------
   ```

This bug **only happens** when the structure of the glade is changed. See the table below for a better understanding about how the structure of the glade has been changed by commit 8405e75:

<details>
<summary>View Table</summary>
<table>
<tr>
<th>Model Heirarchy Before</th>
<th>Model View Before</th>
</tr>

<tr>
<td>

image
</td>

<td>

```
+-------+-------------------+
|       |Title Label        |
| Image |Body Label         |
|       |      buttons      |
|       |    App Icon & Name|
+-------+-------------------+

```
</td>

<tr>
<th>Model Heirarchy After</th>
<th>Model View After</th>
</tr>

<tr>
<td>

image
</td>

<td>

```
+-------+-------------------+
|       |Title Label        |
| Image |Body Label         |
|       |    App Icon & Name|
+-------+-------------------+
|          buttons          |
+---------------------------+
```
</td>
</tr>
</table>
</details>

Ultimately, I really don't know where this bug could be coming from. I can always submit this PR without the moving of the button box, but if we *do* want this feature (which we should, since it looks wayy better IMO), I really need some guidance @phuhl.

**Comment by MyriaCore** [comment]
I think that I do still wanna go through with [this](https://github.com/phuhl/linux_notification_center/issues/75#issuecomment-681123153), it's taking too long to implement for the scope of #75. It might make more sense to live as its own being, or as a part of #77, since it'd be the first step to implementing that anyways. 

I'll revert this commit and do some last look-overs. Otherwise, this PR is basically done.

**Comment by phuhl** [comment]
I think, splitting this into two PRs is a good idea! Btw, I also know now, why your buttons don't appear. It is not, because they are hidden, but because of the rather hacky way that I use to set the notification size. Look at line 176 of NotificationPopup.hs. It returns the height of the notification by receiving the preferred height for a set width. I do it like that, because at the point of writing, gtk did not have a feature to set the width directly, only the height. What I did is the following: Get the "preferred height" at the desired width. Set the height to the preferred height and hope, that the width is correct then. That is also the reason why the notification center bugs arround in #40 I think.

Anyways, back to your buttons. I set the height of the notification by setting it on the label in the background (that is the only reason why it is there). Since you changed the glade's layout, the buttons are not taken into account when calculating the height so they stick out to the bottom of the notification. To prove it: return (a + 100) and find that your buttons are totally visible.

**Comment by phuhl** [comment]
Some more pointers here (and also the reasons why I did not implement image align as center by default): When not setting a line limit, it is buggy! I don't know how to fix it. Actually, it seems to be buggy even with `shortenBody = 5` but without margins, see second screenshot.

Config:
```
imageMarginTop = 0
imageMarginBottom = 0
imageMarginLeft = 15
imageMarginRight = 0

shortenBody = -1

imageAlignment = center
```

org_20200831_095805_2xMNMf

org_20200831_100227_4CAxCX

**Comment by phuhl** [comment]
I will leave this open for now. I don't know a solution for the vertical centering of the image. But I'd like to know your opinion before moving on.

My concern here is, that we already have a good selection of bugs and I am not sure if it is beneficial to push a broken-ish feature just to have more configuration options. But I also see, that you might be able to hack-config your way around this (which is a terrible UX though).

**Comment by MyriaCore** [comment]
Lol yeah I ran into some weird UX with margins and centered images. I'll look over some of these bugs later

**Comment by MyriaCore** [comment]
Alright, I was able to reproduce some of the [bugs you talked about](https://github.com/phuhl/linux_notification_center/pull/78#issuecomment-683630855)! I have a few notes:

- The bug in the image below happens with `shortenBody = 5` AND `shortenBody = -1`, so it appears that this is a bug *specifically relating* to the vertical centering. 
  image
- There does seem to be a lot of jank relating to use of margins *with* use of image centered. I think that these problems basically go away overnight if we just disallow that. So maybe whenever `imageAlignment` is `center`, we should ignore the user's preference for `imageMarginTop` and imageMarginRight`. That won't resolve anything of these bugs, but it'll make for a better UX I think. 

I still can't reproduce the first image. I'll work on getting to the bottom of the other one though.

**Comment by MyriaCore** [comment]
I think that the image cutoff one is bugged cause of the getHeight function, as you talked about:

https://github.com/phuhl/linux_notification_center/blob/499c75b04ab1c06239d9d516c7354d5a96c8d4da/src/NotificationCenter/Notifications/NotificationPopup.hs#L173-L176

Could we just directly set the height to `getHeight (view dContainer dispNotiWithoutHeight) config`?

**Comment by MyriaCore** [comment]
Did you reproduce this with the button swap patch?

image

**Comment by phuhl** [comment]
> Did you reproduce this with the button swap patch?
> 
> image
> 

no, i think this was an the commit after the revert. But it might actually be the same bug, just with more extreme visuals. When the IMG is centered, somehow the container it is centered in behaives as if it was twice as high as the notification or something like that. so, more lines of text -> more offset (I think)

**Comment by phuhl** [comment]
> Could we just directly set the height to getHeight (view dContainer dispNotiWithoutHeight) config?

Not sure what you mean...

**Comment by phuhl** [comment]
> There does seem to be a lot of jank relating to use of margins with use of image centered.

Not sure if it is due to that, but if it was like that, your proposal would be fine for now.

**Comment by MyriaCore** [comment]
> Not sure what you mean...

Not rly sure what I thought I meant, either. I kinda feel like the height setting stuff is where most of our problems come from, so I wanna try to see if I can't just let it do its thing. 

I mean, don't Gtk elements naturally grow to encompass everything they need? i might fiddle around w/ it to see if that's where the bug is.

If I can't implement this by the end of the week, I might just gut the vertical alignment bits and just ship the margins & text ellipsization, since those two solve a lot of the problems that I have with the current layout.

**Comment by MyriaCore** [comment]
Didn't get any time, so since it's friday, I'll prob gut the alignment stuff rn and open a new issue for it. It'll just be the ellipsization and margins, which IMO make for an OK experience anyways.

**Comment by MyriaCore** [comment]
@phuhl lmk if any of these bugs persist, or if new bugs appear!

**Comment by MyriaCore** [comment]
thanks for the merge! :rocket:

**Pull request merged**
